export const GET_PRODUCT_EXITO = "GET_PRODUCT_EXITO";
export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const ADJUST_ITEM_QTY = "ADJUST_ITEM_QTY";



